version: "3.8"

services:
  leave_a_message:
    build: .
    restart: unless-stopped
    networks:
      - nginx_net
    environment:
      LAM_CONFIG: /run/secrets/lam_config
    secrets:
      - lam_config

networks:
  nginx_net:
    name: nginx_net

secrets:
  lam_config:
    file: test.json
